# Generated by Django 6.1 on 2026-08-19 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpatient',
            name='patient_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_patient_refs', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='clinicaltrial',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='doctors.doctorpatient'),
        ),
        migrations.AddField(
            model_name='doctorreport',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='doctorsession',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='doctorsettings',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='healthtimelineentry',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctors.doctorpatient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='trial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.clinicaltrial'),
        ),
    ]
